version: "3.9"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017
      - PORT=50051
    restart: on-failure
    depends_on:
      - db
    ports:
      - "50051:50051"