version: "3.9"

services:
  graph:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
  db:
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017
      - PORT=50051
    restart: on-failure
    depends_on:
      - db
    ports:
      - "50051:50051"