apiVersion: v1
kind: Service
metadata:
  namespace: kic
  name: kic-friends-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc-web
  selector:
    app: kic-friends
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kic
  name: kic-friends
spec:
  selector:
    matchLabels:
      app: kic-friends
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kic
      labels:
        app: kic-friends
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          name: kic-friends
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: PROD
              value: "true"
            - name: PORT
              value: "50051"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: mongo-uri
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graph-neo4j-secrets
                  key: neo4j-password