# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/feed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/feed.proto',
  package='kic.feed',
  syntax='proto3',
  serialized_options=b'Z\022./proto/feed;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10proto/feed.proto\x12\x08kic.feed\x1a\x12proto/common.proto\"4\n\x1aGenerateFeedForUserRequest\x12\x16\n\x06userID\x18\x01 \x01(\x03R\x06userID\"K\n\x1bGenerateFeedForUserResponse\x12,\n\x08\x66ileInfo\x18\x01 \x01(\x0b\x32\x10.kic.common.FileR\x08\x66ileInfo2l\n\x04\x46\x65\x65\x64\x12\x64\n\x13GenerateFeedForUser\x12$.kic.feed.GenerateFeedForUserRequest\x1a%.kic.feed.GenerateFeedForUserResponse0\x01\x42\x14Z\x12./proto/feed;protob\x06proto3'
  ,
  dependencies=[proto_dot_common__pb2.DESCRIPTOR,])




_GENERATEFEEDFORUSERREQUEST = _descriptor.Descriptor(
  name='GenerateFeedForUserRequest',
  full_name='kic.feed.GenerateFeedForUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='kic.feed.GenerateFeedForUserRequest.userID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='userID', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=102,
)


_GENERATEFEEDFORUSERRESPONSE = _descriptor.Descriptor(
  name='GenerateFeedForUserResponse',
  full_name='kic.feed.GenerateFeedForUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileInfo', full_name='kic.feed.GenerateFeedForUserResponse.fileInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='fileInfo', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=179,
)

_GENERATEFEEDFORUSERRESPONSE.fields_by_name['fileInfo'].message_type = proto_dot_common__pb2._FILE
DESCRIPTOR.message_types_by_name['GenerateFeedForUserRequest'] = _GENERATEFEEDFORUSERREQUEST
DESCRIPTOR.message_types_by_name['GenerateFeedForUserResponse'] = _GENERATEFEEDFORUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateFeedForUserRequest = _reflection.GeneratedProtocolMessageType('GenerateFeedForUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEFEEDFORUSERREQUEST,
  '__module__' : 'proto.feed_pb2'
  # @@protoc_insertion_point(class_scope:kic.feed.GenerateFeedForUserRequest)
  })
_sym_db.RegisterMessage(GenerateFeedForUserRequest)

GenerateFeedForUserResponse = _reflection.GeneratedProtocolMessageType('GenerateFeedForUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEFEEDFORUSERRESPONSE,
  '__module__' : 'proto.feed_pb2'
  # @@protoc_insertion_point(class_scope:kic.feed.GenerateFeedForUserResponse)
  })
_sym_db.RegisterMessage(GenerateFeedForUserResponse)


DESCRIPTOR._options = None

_FEED = _descriptor.ServiceDescriptor(
  name='Feed',
  full_name='kic.feed.Feed',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=181,
  serialized_end=289,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateFeedForUser',
    full_name='kic.feed.Feed.GenerateFeedForUser',
    index=0,
    containing_service=None,
    input_type=_GENERATEFEEDFORUSERREQUEST,
    output_type=_GENERATEFEEDFORUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEED)

DESCRIPTOR.services_by_name['Feed'] = _FEED

# @@protoc_insertion_point(module_scope)
